# World Development Indicators Dataset

## Contents
1. Setup

## 1. Setup

In [4]:
%python
wdi_basedir = '/dbfs/mnt/datalab-datasets/ma705/WDI_csv/'

In [5]:
%r
wdi_basedir = '/dbfs/mnt/datalab-datasets/ma705/WDI_csv/'

### `WDI` using SQL

In [7]:
%sql
drop table if exists wdi

In [8]:
%sql
create temporary table wdi
using CSV 
options(path="/mnt/datalab-datasets/ma705/WDI_csv//WDIData.csv", 
        header=TRUE)

In [9]:
%sql
select *
from wdi
limit 3

__The End__