# Essentials - Values & Variables

Source: Chapter 16. Vectors from 
R for Data Science
by Garrett Grolemund; Hadley Wickham
Published by O'Reilly Media, Inc., 2016 
(http://r4ds.had.co.nz, [Amazon](http://amzn.to/2aHLAQ1))

### Table of contents

1. Types of values 
2. Classes of values
3. Special values
4. Missing values 
5. Test functions
6. Coercion
7. Variables

The following command indicates the version of R running in this notebook, or more accurately on the cluster to which this notebook is attached.

###
__hei__

In [5]:
%r 
R.Version()$version.string

There are two ways to classify values in R:
1. by type, which indicates how they are stored
2. by class, which indicates how they are used

There are five __types__ of values in R: character, double, integer, logical and complex. Double values can be any number. Integer values can only be whole numbers. Complex numbers contain real and imaginary parts.

In [8]:
%r 
typeof("Welcome!")

In [9]:
%r  
typeof(3.14159)

The number `5` is also stored as a `double` in R.

In [11]:
%r 
typeof(5)

An integer number can be stored as an `integer` by writing the number with a capital `L` at the end. 

For example,

In [13]:
%r 
typeof(98L)

There are two logical values: `TRUE`, `FALSE`.

In [15]:
%r 
typeof(TRUE)

In [16]:
%r 
 typeof(FALSE)

In [17]:
%r 
typeof(1+4i)

R recognizes `pi` as a value

In [19]:
%r 
typeof(pi)

Many R objects (values) have a _class attribute_ that indicates how that object can be used. 

There are three basic class attributes, though there are many more. They are:

In [21]:
%r 
class("hello")

In [22]:
%r 
class(1.9)

In [23]:
%r 
class(TRUE)

### Special values

#### Doubles

There are four special double values: `-Inf`, `Inf`, `NaN` and `NA`.

There are three special integer values: `-Inf`, `Inf` and `NA`.

A calculation will result in `Inf` or `-Inf` if it exceeds the capacity of R to store it. 

This happens in at least these two cases:
1. The result is too large
1. Dividing by zero

In [27]:
%r 
2^10000000000000000000000000000000000000

In [28]:
%r 
-2^100000

In [29]:
%r 
1/0

There is one instance I know about where a calculation will result in `NaN` (not a number.) 

This is `0/0`.

In [31]:
%r 
0/0

Often `NA` is the result when R expects to read in a number but is given something that is not a number. 

For instance,

In [33]:
%r 
as.numeric("this isn't a number")

In [34]:
%r 
as.numeric("123")

In [35]:
a <- c("He says,'my name is Leo'")
a

In [36]:
%r 
as.character(234)

### Logical Values

There are two logical values: `TRUE`, `FALSE`.

In [38]:
%r 
typeof(FALSE)

In [39]:
%r 
typeof(TRUE)

### Missing values

Each of these types have their own missing value, but in most cases we will see `NA`.

In [41]:
%r 
typeof(NA_integer_)

In [42]:
%r 
typeof(NA_real_)

In [43]:
%r 
typeof(NA_character_)

The `NA` value is of type logical.

In [45]:
%r 
typeof(NA)

### Test Functions

There are a handful of functions that test values: `is.finite`, `is.infinite`, `is.na`, `is.nan`.

In [47]:
%r 
is.finite(56)

In [48]:
%r 
is.finite(3/0)

In [49]:
is.na(a)

In [50]:
%r 
is.infinite(3/0)

In [51]:
%r 
is.na(NA)

In [52]:
%r 
is.nan(0/0)

### Coercion

Values of one type can be converted to another type. This can happen explicitly or implicitly.

#### Explicit Coercion

In [55]:
%r 
as.logical(0)

In [56]:
%r 
as.logical(1)

In [57]:
as.logical(0/0)

In [58]:
%r 
as.logical("True")

In [59]:
%r 
as.integer(5.812367)

In [61]:
%r 
as.double("3")

#### Implicit Coercion

In [63]:
%r 
TRUE + 2

In [64]:
%r 
FALSE * 3

In [65]:
%r 
3.4 * 2

### Variables

Values can be stored in variables in three ways:
1. With the equal sign `=`
2. With the left arrow `<-`
3. With the right arrow `->`

Recall that notebook code cells return the last value when they are run.

In [68]:
%r 
x = "Hello"

In [69]:
%r 
x

In [70]:
%r 
x=5
x

In [71]:
%r 
5 -> a

In [72]:
%r 
a

In [73]:
%r 
z = TRUE

In [74]:
%r 
z

__The End__